# Generated by Django 5.1.2 on 2024-11-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_havaalanlari_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucuslar',
            old_name='donus_zamani',
            new_name='inis_zamani',
        ),
    ]
